version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test:unit
  deploy_dev:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git merge dev && git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_DEV.git master
  deploy_stg:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STG.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy_stg:
          requires:
            - build
          filters:
            branches:
              only: master
